CREATE TABLE games(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    game_id VARCHAR2(150) CONSTRAINT games__not_null__game_id NOT NULL,
    time_ping NUMBER CONSTRAINT games__not_null__time_ping NOT NULL,
    time_pong NUMBER CONSTRAINT games__not_null__time_pong NOT NULL,
    rounds_played NUMBER CONSTRAINT games__not_null_rounds_played NOT NULL,
    winner VARCHAR(15),
    PRIMARY KEY (id)
);