spring:
  artemis:
    broker-url: ${ARTEMIS_URL:tcp://localhost:61616}
    user: ${ARTEMIS_USERNAME:artemis}
    password: ${ARTEMIS_PASSWORD:artemis}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_HOST:localhost:9092}
      group-id: pong
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        'spring.json.value.default.type': de.consol.dus.pong.game.Game
  jmx:
    enabled: true
server:
  port: 8081
web-clients:
  reporter:
    base-url: ${REPORTER_BASE_URL:http://localhost:8082/reports}
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    metrics:
      enabled: true
    env:
      enabled: true
messaging:
  activemq:
    destination: messages-activemq
  kafka:
    destination: messages-kafka
    group-id: pong

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080
web-clients:
  reporter:
    base-url: ${REPORTER_BASE_URL:http://localhost:8082/reports}

---
spring:
  config:
    activate:
      on-profile: json-logging
logging:
  config: classpath:log4j2-prod.yml