server:
  port: ${HTTP_PORT:8080}
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:${DB_TYPE:postgresql}://${DB_HOST:localhost:5432}/${DB_NAME:reporter}
    username: ${DB_USER:reporter}
    password: ${DB_PASSWORD:reporter}
  jmx:
    enabled: true