server:
  port: ${HTTP_PORT:8080}
web-clients:
  reporter:
    base-url: ${REPORTER_BASE_URL:http://localhost:8082/reports}
spring:
  artemis:
    broker-url: ${ARTEMIS_URL:tcp://localhost:61616}
    user: ${ARTEMIS_USERNAME:artemis}
    password: ${ARTEMIS_PASSWORD:artemis}
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_HOST:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        'spring.json.add.type.headers': false
  jmx:
    enabled: true